export const enum FileModelType {
  DEPRECIATION_UPLOAD = 'DEPRECIATION_UPLOAD',
  ACQUISITION_UPLOAD = 'ACQUISITION_UPLOAD',
  DISPOSAL_UPLOAD = 'DISPOSAL_UPLOAD',
  CWIP_UPLOAD = 'CWIP_UPLOAD',
  CWIP_TRANSFER_UPLOAD = 'CWIP_TRANSFER_UPLOAD',
  ASSET_ITEM_UPLOAD = 'ASSET_ITEM_UPLOAD'
}
